version: 2

project_name: fp-multiuser

builds:
  - id: fp-multiuser
    main: ./cmd/fp-multiuser
    binary: fp-multiuser
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

upx:
  - enabled: true
    ids:
      - fp-multiuser
    goos:
      - linux
      - windows
    compress: best

archives:
  - id: fp-multiuser
    ids:
      - fp-multiuser
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    files:
      - LICENSE

checksum:
  name_template: '{{ .ProjectName }}_sha256_checksums.txt'
  algorithm: sha256

release:
  draft: false
